// Generated by js_of_ocaml 2.8.1
(function(l){"use strict";var
aa=254,N="Sys_error",$=224,_="Invalid_argument",Y=250,Z="function",n=1024,M=57343,X=512,W="End_of_file",V="Failure",L="Undefined_recursive_module",U="Stack_overflow",c=128,e="",x=" : file already exists",I=2048,J=56320,K=240,b=248,T="Not_found",G="Assert_failure",H="/",R="Sys_blocked_io",S="fd ",F="Out_of_memory",Q="Match_failure",P="Division_by_zero",O=1e3,aE=0;function
h(){return aE++}function
ay(){var
b=l.console?l.console:{},c=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
ad(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aQ(g){for(var
h=e,b=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<c){for(var
f=d+1;f<i&&(a=g.charCodeAt(f))<c;f++);if(f-d>X){b.substr(0,1);h+=b;b=e;h+=g.slice(d,f)}else
b+=g.slice(d,f);if(f==i)break;d=f}if(a<I){b+=String.fromCharCode(192|a>>6);b+=String.fromCharCode(c|a&63)}else
if(a<55296||a>=M)b+=String.fromCharCode($|a>>12,c|a>>6&63,c|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<J||j>M)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;b+=String.fromCharCode(K|a>>18,c|a>>12&63,c|a>>6&63,c|a&63)}if(b.length>n){b.substr(0,1);h+=b;b=e}}return h+b}function
aI(b,a){if(a.repeat)return a.repeat(b);var
c=e,d=0;if(b==0)return c;for(;;){if(b&1)c+=a;b>>=1;if(b==0)return c;a+=a;d++;if(d==9)a.slice(0,1)}}function
aT(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
A(b,c,a){var
d=String.fromCharCode;if(c==0&&a<=4096&&a==b.length)return d.apply(null,b);var
f=e;for(;0<a;c+=n,a-=n)f+=d.apply(null,aT(b,c,Math.min(a,n)));return f}function
p(a){if(a.t==2)a.c+=aI(a.l-a.c.length,"\0");else
a.c=A(a.c,0,a.c.length);a.t=0}function
aP(g){for(var
l=e,d=e,i,h,j,a,b=0,k=g.length;b<k;b++){h=g.charCodeAt(b);if(h<c){for(var
f=b+1;f<k&&(h=g.charCodeAt(f))<c;f++);if(f-b>X){d.substr(0,1);l+=d;d=e;l+=g.slice(b,f)}else
d+=g.slice(b,f);if(f==k)break;b=f}a=1;if(++b<k&&((j=g.charCodeAt(b))&-64)==c){i=j+(h<<6);if(h<$){a=i-12416;if(a<c)a=1}else{a=2;if(++b<k&&((j=g.charCodeAt(b))&-64)==c){i=j+(i<<6);if(h<K){a=i-925824;if(a<I||a>=55295&&a<57344)a=2}else{a=3;if(++b<k&&((j=g.charCodeAt(b))&-64)==c&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),J+(a&1023));else
d+=String.fromCharCode(a);if(d.length>n){d.substr(0,1);l+=d;d=e}}return l+d}function
aN(a){switch(a.t){case
9:return a.c;default:p(a);case
0:if(ad(a.c)){a.t=9;return a.c}a.t=8;case
8:return aP(a.c)}}function
f(c,a,b){this.t=c;this.c=a;this.l=b}f.prototype.toString=function(){return aN(this)};function
ae(a){var
b=9;if(!ad(a))b=8,a=aQ(a);return new
f(b,a,a.length)}var
d=[0];function
aF(b,a){throw[0,b,a]}function
a(a){return new
f(0,a,a.length)}function
ah(c,b){aF(c,a(b))}function
q(a){ah(d.Invalid_argument,a)}function
m(a){if(a<0)q("String.create");return new
f(a?2:9,e,a)}var
ai=0;function
aU(){return new
Date().getTime()/O}function
B(){return Math.floor(aU())}function
j(b){this.data=b;this.inode=ai++;var
a=B();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={truncate:function(){this.data=m(0);this.modified()},modified:function(){var
a=B();this.atime=a;this.mtime=a}};function
z(a){return a.l}function
i(a){ah(d.Sys_error,a)}function
ag(a){a=a
instanceof
f?a.toString():a;i(a+": No such file or directory")}var
au=H;function
r(a){a=a
instanceof
f?a.toString():a;if(a.charCodeAt(0)!=47)a=au+a;var
d=a.split(H),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
k(){this.content={};this.inode=ai++;var
a=B();this.atime=a;this.mtime=a;this.ctime=a}k.prototype={exists:function(a){return this.content[a]?1:0},mk:function(b,a){this.content[b]=a},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
s=new
k();s.mk(e,new
k());function
y(c){var
a=s;for(var
b=0;b<c.length;b++){if(!(a.exists&&a.exists(c[b])))ag(c.orig);a=a.get(c[b])}return a}function
aM(b){var
c=r(b),a=y(c);return a
instanceof
k?1:0}function
aK(a){return new
f(4,a,a.length)}function
ac(b){if(l.Uint8Array)var
c=new(l.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
aV(a){if(a.t!=4)ac(a);return a.c}function
av(l,c){var
e=r(l),b=s;for(var
g=0;g<e.length-1;g++){var
d=e[g];if(!b.exists(d))b.mk(d,new
k());b=b.get(d);if(!(b
instanceof
k))i(e.orig+x)}var
d=e[e.length-1];if(b.exists(d))i(e.orig+x);if(c
instanceof
k)b.mk(d,c);else
if(c
instanceof
j)b.mk(d,c);else
if(c
instanceof
f)b.mk(d,new
j(c));else
if(c
instanceof
Array)b.mk(d,new
j(aK(c)));else
if(c.toString){var
h=a(c.toString());b.mk(d,new
j(h))}else
q("caml_fs_register");return 0}function
aL(f){var
a=s,c=r(f),d,e;for(var
b=0;b<c.length;b++){if(a.auto){d=a.auto;e=b}if(!(a.exists&&a.exists(c[b])))return d?d(c,e):0;a=a.get(c[b])}return 1}function
o(c,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?z(e.data):0;b.flags=a;d.fds[c]=b;d.fd_last_idx=c;return c}function
aW(b,e,j){var
a={};while(e){switch(e[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}e=e[2]}var
f=b.toString(),h=r(b);if(a.rdonly&&a.wronly)i(f+" : flags Open_rdonly and Open_wronly are not compatible");if(a.text&&a.binary)i(f+" : flags Open_text and Open_binary are not compatible");if(aL(b)){if(aM(b))i(f+" : is a directory");if(a.create&&a.excl)i(f+x);var
g=d.fd_last_idx?d.fd_last_idx:0,c=y(h);if(a.truncate)c.truncate();return o(g+1,c,a)}else
if(a.create){var
g=d.fd_last_idx?d.fd_last_idx:0;av(b,m(0));var
c=y(h);return o(g+1,c,a)}else
ag(b)}o(0,new
j(m(0)));o(1,new
j(m(0)));o(2,new
j(m(0)));function
az(b){var
a=d.fds[b];if(a.flags.wronly)i(S+b+" is writeonly");return{file:a.file,offset:a.offset,fd:b,opened:true,refill:null}}function
ab(d,e,a,f,c){if(c==0)return 0;if(f==0&&(c>=a.l||a.t==2&&c>=a.c.length)){a.c=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else
if(a.t==2&&f==a.c.length){a.c+=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else{if(a.t!=4)ac(a);var
g=d.c,h=a.c;if(d.t==4)for(var
b=0;b<c;b++)h[f+b]=g[e+b];else{var
i=Math.min(c,g.length-e);for(var
b=0;b<i;b++)h[f+b]=g.charCodeAt(e+b);for(;b<c;b++)h[f+b]=0}}return 0}function
aR(a){var
b=l;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aS(a){var
b=l;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}var
aA=new
Array();function
aH(b,h){var
g=a(h),c=z(g),f=z(b.file.data),e=b.offset;if(e+c>=f){var
d=m(e+c);ab(b.file.data,0,d,0,f);ab(g,0,d,e,c);b.file.data=d}b.offset+=c;b.file.modified();return 0}function
af(a){var
b;switch(a){case
1:b=aS;break;case
2:b=aR;break;default:b=aH}var
f=d.fds[a];if(f.flags.rdonly)i(S+a+" is readonly");var
c={file:f.file,offset:f.offset,fd:a,opened:true,buffer:e,output:b};aA[c.fd]=c;return c}function
aw(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
ax(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
aJ(a,b){a.t&6&&p(a);b.t&6&&p(b);return a.c<b.c?-1:a.c>b.c?1:0}function
at(a,b,i){var
d=[];for(;;){if(!(i&&a===b))if(a
instanceof
f)if(b
instanceof
f){if(a!==b){var
c=aJ(a,b);if(c!=0)return c}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
e=a[0];if(e===aa)e=0;if(e===Y){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
g=b[0];if(g===aa)g=0;if(g===Y){b=b[1];continue}else
if(e!=g)return e<g?-1:1;else
switch(e){case
248:var
c=ax(a[2],b[2]);if(c!=0)return c;break;case
251:q("equal: abstract value");case
255:var
c=aw(a,b);if(c!=0)return c;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)d.push(a,b,1)}}else
return 1}else
if(b
instanceof
f||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!="number"&&a&&a.compare)return a.compare(b,i);else
if(typeof
a==Z)q("equal: functional value");else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!i)return NaN;if(a==a)return 1;if(b==b)return-1}}if(d.length==0)return 0;var
h=d.pop();b=d.pop();a=d.pop();if(h+1<a.length)d.push(a,b,h+1);a=a[h];b=b[h]}}function
aC(a,b){return+(at(a,b,false)!=0)}function
aD(a){return a
instanceof
Array?a[0]:a
instanceof
f?252:O}function
g(c,b,a){d[c+1]=b;if(a)d[a]=b}var
aB={};function
as(a){if((a.t&6)!=0)p(a);return a.c}function
aG(a,b){aB[as(a)]=b;return 0}function
aO(c,a){if(typeof
a===Z){c.fun=a;return 0}if(a.fun){c.fun=a.fun;return 0}var
b=a.length;while(b--)c[b]=a[b];return 0}var
w=a("Something wrong");g(11,[b,a(L),-12],L);g(10,[b,a(G),-11],G);g(9,[b,a(R),-10],R);g(8,[b,a(U),-9],U);g(7,[b,a(Q),-8],Q);g(6,[b,a(T),-7],T);g(5,[b,a(P),-6],P);g(4,[b,a(W),-5],W);g(3,[b,a(_),-4],_);g(2,[b,a(V),-3],V);g(1,[b,a(N),-2],N);g(0,[b,a(F),-1],F);h(0);az(0);af(1);af(2);h(0);h(0);h(0);h(0);h(0);var
C=[0,0],an=a("Js.Error"),aq=a("QuaPervasives.Error.Runtime");function
D(a){C[1]=[0,a,C[1]];return 0}h(0);h(0);var
t=[];aO(t,[0,t,t]);var
u=l,am=u.Array,E=[b,an,h(0)],v=[0,E,{}],ak=undefined,al=false,aj=aD(v)===b?v:v[1];aG(a("jsError"),aj);(function(a){throw a});D(function(a){return a[1]===E?[0,ae(a[2].toString())]:0});D(function(a){return a
instanceof
am?0:[0,ae(a.toString())]});h(0);u.HTMLElement===ak;var
ao=ay(0);function
ap(b){try{var
a=aC($QUASAR_DEBUG,al);return a}catch(a){return 0}}var
ar=[b,aq,h(0)];if(ap(0)){u.alert(w.toString());ao.log(w)}throw[0,ar,w]}(function(){return this}()));
