// Generated by js_of_ocaml 2.8.1
(function(o){"use strict";var
ab=254,O="Sys_error",aa=224,$="Invalid_argument",Z=250,_="function",m=1024,N=57343,Y=512,X="End_of_file",W="Failure",M="Undefined_recursive_module",V="Stack_overflow",d=128,b="",x=" : file already exists",J=2048,K=56320,L=240,c=248,U="Not_found",H="Assert_failure",I="/",S="Sys_blocked_io",T="fd ",G="Out_of_memory",R="Match_failure",Q="Division_by_zero",P=1e3,aF=0;function
h(){return aF++}function
ae(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aR(g){for(var
h=b,c=h,a,j,e=0,i=g.length;e<i;e++){a=g.charCodeAt(e);if(a<d){for(var
f=e+1;f<i&&(a=g.charCodeAt(f))<d;f++);if(f-e>Y){c.substr(0,1);h+=c;c=b;h+=g.slice(e,f)}else
c+=g.slice(e,f);if(f==i)break;e=f}if(a<J){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(d|a&63)}else
if(a<55296||a>=N)c+=String.fromCharCode(aa|a>>12,d|a>>6&63,d|a&63);else
if(a>=56319||e+1==i||(j=g.charCodeAt(e+1))<K||j>N)c+="\xef\xbf\xbd";else{e++;a=(a<<10)+j-56613888;c+=String.fromCharCode(L|a>>18,d|a>>12&63,d|a>>6&63,d|a&63)}if(c.length>m){c.substr(0,1);h+=c;c=b}}return h+c}function
aJ(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aU(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
A(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=m,a-=m)f+=e.apply(null,aU(c,d,Math.min(a,m)));return f}function
p(a){if(a.t==2)a.c+=aJ(a.l-a.c.length,"\0");else
a.c=A(a.c,0,a.c.length);a.t=0}function
aQ(g){for(var
l=b,e=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<d){for(var
f=c+1;f<k&&(h=g.charCodeAt(f))<d;f++);if(f-c>Y){e.substr(0,1);l+=e;e=b;l+=g.slice(c,f)}else
e+=g.slice(c,f);if(f==k)break;c=f}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==d){i=j+(h<<6);if(h<aa){a=i-12416;if(a<d)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==d){i=j+(i<<6);if(h<L){a=i-925824;if(a<J||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==d&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;e+="\ufffd"}else
if(a>65535)e+=String.fromCharCode(55232+(a>>10),K+(a&1023));else
e+=String.fromCharCode(a);if(e.length>m){e.substr(0,1);l+=e;e=b}}return l+e}function
aO(a){switch(a.t){case
9:return a.c;default:p(a);case
0:if(ae(a.c)){a.t=9;return a.c}a.t=8;case
8:return aQ(a.c)}}function
f(c,a,b){this.t=c;this.c=a;this.l=b}f.prototype.toString=function(){return aO(this)};function
af(a){var
b=9;if(!ae(a))b=8,a=aR(a);return new
f(b,a,a.length)}function
aG(b,a){throw[0,b,a]}function
a(a){return new
f(0,a,a.length)}function
ai(c,b){aG(c,a(b))}var
e=[0];function
i(a){ai(e.Sys_error,a)}function
az(a){if(!a.opened)i("Cannot flush a closed channel");if(a.buffer==b)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=b;return 0}function
q(a){ai(e.Invalid_argument,a)}function
l(a){if(a<0)q("String.create");return new
f(a?2:9,b,a)}var
aj=0;function
aV(){return new
Date().getTime()/P}function
B(){return Math.floor(aV())}function
j(b){this.data=b;this.inode=aj++;var
a=B();this.atime=a;this.mtime=a;this.ctime=a}j.prototype={truncate:function(){this.data=l(0);this.modified()},modified:function(){var
a=B();this.atime=a;this.mtime=a}};function
z(a){return a.l}function
ah(a){a=a
instanceof
f?a.toString():a;i(a+": No such file or directory")}var
av=I;function
r(a){a=a
instanceof
f?a.toString():a;if(a.charCodeAt(0)!=47)a=av+a;var
e=a.split(I),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
k(){this.content={};this.inode=aj++;var
a=B();this.atime=a;this.mtime=a;this.ctime=a}k.prototype={exists:function(a){return this.content[a]?1:0},mk:function(b,a){this.content[b]=a},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
t=new
k();t.mk(b,new
k());function
y(c){var
a=t;for(var
b=0;b<c.length;b++){if(!(a.exists&&a.exists(c[b])))ah(c.orig);a=a.get(c[b])}return a}function
aN(b){var
c=r(b),a=y(c);return a
instanceof
k?1:0}function
aL(a){return new
f(4,a,a.length)}function
ad(b){if(o.Uint8Array)var
c=new(o.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
aW(a){if(a.t!=4)ad(a);return a.c}function
aw(l,c){var
e=r(l),b=t;for(var
g=0;g<e.length-1;g++){var
d=e[g];if(!b.exists(d))b.mk(d,new
k());b=b.get(d);if(!(b
instanceof
k))i(e.orig+x)}var
d=e[e.length-1];if(b.exists(d))i(e.orig+x);if(c
instanceof
k)b.mk(d,c);else
if(c
instanceof
j)b.mk(d,c);else
if(c
instanceof
f)b.mk(d,new
j(c));else
if(c
instanceof
Array)b.mk(d,new
j(aL(c)));else
if(c.toString){var
h=a(c.toString());b.mk(d,new
j(h))}else
q("caml_fs_register");return 0}function
aM(f){var
a=t,c=r(f),d,e;for(var
b=0;b<c.length;b++){if(a.auto){d=a.auto;e=b}if(!(a.exists&&a.exists(c[b])))return d?d(c,e):0;a=a.get(c[b])}return 1}function
n(c,d,a){if(e.fds===undefined)e.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?z(d.data):0;b.flags=a;e.fds[c]=b;e.fd_last_idx=c;return c}function
aX(b,d,j){var
a={};while(d){switch(d[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}d=d[2]}var
f=b.toString(),h=r(b);if(a.rdonly&&a.wronly)i(f+" : flags Open_rdonly and Open_wronly are not compatible");if(a.text&&a.binary)i(f+" : flags Open_text and Open_binary are not compatible");if(aM(b)){if(aN(b))i(f+" : is a directory");if(a.create&&a.excl)i(f+x);var
g=e.fd_last_idx?e.fd_last_idx:0,c=y(h);if(a.truncate)c.truncate();return n(g+1,c,a)}else
if(a.create){var
g=e.fd_last_idx?e.fd_last_idx:0;aw(b,l(0));var
c=y(h);return n(g+1,c,a)}else
ah(b)}n(0,new
j(l(0)));n(1,new
j(l(0)));n(2,new
j(l(0)));function
aA(b){var
a=e.fds[b];if(a.flags.wronly)i(T+b+" is writeonly");return{file:a.file,offset:a.offset,fd:b,opened:true,refill:null}}function
ac(d,e,a,f,c){if(c==0)return 0;if(f==0&&(c>=a.l||a.t==2&&c>=a.c.length)){a.c=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else
if(a.t==2&&f==a.c.length){a.c+=d.t==4?A(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);a.t=a.c.length==a.l?0:2}else{if(a.t!=4)ad(a);var
g=d.c,h=a.c;if(d.t==4)for(var
b=0;b<c;b++)h[f+b]=g[e+b];else{var
i=Math.min(c,g.length-e);for(var
b=0;b<i;b++)h[f+b]=g.charCodeAt(e+b);for(;b<c;b++)h[f+b]=0}}return 0}function
aS(a){var
b=o;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
aT(a){var
b=o;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}var
s=new
Array();function
aI(b,h){var
g=a(h),c=z(g),f=z(b.file.data),e=b.offset;if(e+c>=f){var
d=l(e+c);ac(b.file.data,0,d,0,f);ac(g,0,d,e,c);b.file.data=d}b.offset+=c;b.file.modified();return 0}function
ag(a){var
c;switch(a){case
1:c=aT;break;case
2:c=aS;break;default:c=aI}var
f=e.fds[a];if(f.flags.rdonly)i(T+a+" is readonly");var
d={file:f.file,offset:f.offset,fd:a,opened:true,buffer:b,output:c};s[d.fd]=d;return d}function
aB(){var
a=0;for(var
b
in
s)if(s[b].opened)a=[0,s[b],a];return a}function
ax(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
ay(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
aK(a,b){a.t&6&&p(a);b.t&6&&p(b);return a.c<b.c?-1:a.c>b.c?1:0}function
au(a,b,i){var
d=[];for(;;){if(!(i&&a===b))if(a
instanceof
f)if(b
instanceof
f){if(a!==b){var
c=aK(a,b);if(c!=0)return c}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
e=a[0];if(e===ab)e=0;if(e===Z){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
g=b[0];if(g===ab)g=0;if(g===Z){b=b[1];continue}else
if(e!=g)return e<g?-1:1;else
switch(e){case
248:var
c=ay(a[2],b[2]);if(c!=0)return c;break;case
251:q("equal: abstract value");case
255:var
c=ax(a,b);if(c!=0)return c;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)d.push(a,b,1)}}else
return 1}else
if(b
instanceof
f||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!="number"&&a&&a.compare)return a.compare(b,i);else
if(typeof
a==_)q("equal: functional value");else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!i)return NaN;if(a==a)return 1;if(b==b)return-1}}if(d.length==0)return 0;var
h=d.pop();b=d.pop();a=d.pop();if(h+1<a.length)d.push(a,b,h+1);a=a[h];b=b[h]}}function
aD(a,b){return+(au(a,b,false)!=0)}function
aE(a){return a
instanceof
Array?a[0]:a
instanceof
f?252:P}function
g(c,b,a){e[c+1]=b;if(a)e[a]=b}var
aC={};function
at(a){if((a.t&6)!=0)p(a);return a.c}function
aH(a,b){aC[at(a)]=b;return 0}function
aP(c,a){if(typeof
a===_){c.fun=a;return 0}if(a.fun){c.fun=a.fun;return 0}var
b=a.length;while(b--)c[b]=a[b];return 0}g(11,[c,a(M),-12],M);g(10,[c,a(H),-11],H);g(9,[c,a(S),-10],S);g(8,[c,a(V),-9],V);g(7,[c,a(R),-8],R);g(6,[c,a(U),-7],U);g(5,[c,a(Q),-6],Q);g(4,[c,a(X),-5],X);g(3,[c,a($),-4],$);g(2,[c,a(W),-3],W);g(1,[c,a(O),-2],O);g(0,[c,a(G),-1],G);h(0);aA(0);ag(1);ag(2);h(0);h(0);h(0);h(0);h(0);var
C=[0,0],ap=a("Js.Error"),ar=a("En debug"),as=a("Pas en debug");function
D(a){C[1]=[0,a,C[1]];return 0}h(0);h(0);var
u=[];aP(u,[0,u,u]);var
v=o,ao=v.Array,E=[c,ap,h(0)],w=[0,E,{}],am=undefined,an=false,al=aE(w)===c?w:w[1];aH(a("jsError"),al);(function(a){throw a});D(function(a){return a[1]===E?[0,af(a[2].toString())]:0});D(function(a){return a
instanceof
ao?0:[0,af(a.toString())]});h(0);v.HTMLElement===am;function
aq(b){try{var
a=aD($QUASAR_DEBUG,an);return a}catch(a){return 0}}function
F(a){return v.alert(a.toString())}h(0);if(aq(0))F(ar);else
F(as);function
ak(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{az(d)}catch(a){}var
a=c;continue}return 0}}ak(aB(0));return}(function(){return this}()));
